volumes:
  redis_data:

networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_FRONTEND: ${SENTRY_AUTH_FRONTEND}
        SENTRY_AUTH_BACKEND: ${SENTRY_AUTH_BACKEND}
    ports:
      - "8080:4000"
    environment:
      - URL=http://localhost:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - default

