name: Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress:
    runs-on: ubuntu-24.04

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install, generate Prisma, and build backend
        working-directory: ./backend
        run: |
          bun install
          bun run prisma:generate
        env:
          REDIS_HOST: "localhost"
          REDIS_PORT: 6379
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start backend
        working-directory: ./backend
        run: bun run start:dev &
        env:
          REDIS_HOST: "localhost"
          REDIS_PORT: 6379
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies
        run: cd frontend && bun install

      - name: Run Frontend
        run: cd frontend && bun run start:dev &

      - name: Run Cypress
        run: cd frontend && bun run cypress:run
