name: Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress:
    runs-on: ubuntu-24.04

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js with corepack
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Enable Corepack and use pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install, generate Prisma, and build backend
        working-directory: ./backend
        run: |
          pnpm install
          pnpm prisma:generate
          pnpm build
        env:
          REDIS_HOST: "localhost"
          REDIS_PORT: 6379
          DATABASE_URL: "mongodb://localhost:27017/app"

      - name: Start backend
        working-directory: ./backend
        run: pnpm start:dev
        env:
          REDIS_HOST: "localhost"
          REDIS_PORT: 6379
          DATABASE_URL: "mongodb://localhost:27017/app"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

      - name: Start frontend
        working-directory: ./frontend
        run: bun run dev

      - name: Run Cypress tests
        working-directory: ./frontend
        run: bun run cypress:ci
