name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-eslint:
    name: Run Eslint (frontend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: bun install --frozen-lockfile --cwd /app/frontend

      - name: Run ESLint
        run: bun run frontend:lint

  backend-eslint:
    name: Run Eslint (backend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install dependencies
        run: cd backend && pnpm install

      - name: Run ESLint
        run: cd backend && pnpm lint

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-24.04
    needs: frontend-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Set SENTRY_AUTH_TOKEN for frontend
        run: echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_FRONTEND }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install --frozen-lockfile --cwd /app/frontend

      - name: Run Frontend Build
        run: bun run frontend:build

  backend-build:
    name: Build Backend
    runs-on: ubuntu-24.04
    needs: backend-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Set SENTRY_AUTH_TOKEN for backend
        run: echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_BACKEND }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: cd backend && pnpm install

      - name: Run Backend Build
        run: cd backend && pnpm build

  docker-build:
    name: Build Docker Image (Test)
    runs-on: ubuntu-24.04
    needs: [frontend-build, backend-build]

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.image_name }} \
            --build-arg SENTRY_AUTH_FRONTEND=${{ secrets.SENTRY_AUTH_FRONTEND }} \
            --build-arg SENTRY_AUTH_BACKEND=${{ secrets.SENTRY_AUTH_BACKEND }} .
